add resonator Props
tscircuit/props pull request #119
Opened 2024-12-17 10:32 UTC by techmannih

add resonator props
@imrishabh18 please check

2024-12-17 11:46 UTC, imrishabh18 requested changes
Another thing, missed it in the comment before. The ResonatorProps needs to be exported as well from the `index.ts` file.

cc: @seveibar Does these properties look good for resonator? We need it for the arduino nano - https://github.com/tscircuit/core/issues/426

2024-12-18 02:25 UTC, seveibar commented on lib/components/resonator.ts
> +export const resonatorPins = lrPins
This should be removed or changed to reflect the 3 pins, lrPins refers to left/right pins which isnt appropriate for a 3 pin circuit.
```suggestion
```

2024-12-18 02:25 UTC, seveibar approved these changes

2024-12-18 02:25 UTC, seveibar commented
Approved after rishabhs feedback is addressed!

2024-12-18 10:29 UTC, imrishabh18 approved these changes

2024-12-19 09:31 UTC, merged

2024-12-19 09:39 UTC, imrishabh18 commented
@techmannih The bounty is there for the whole issue https://github.com/tscircuit/core/issues/426 which includes this as one of the task.