pushbutton props
tscircuit/props pull request #84
Opened 2024-11-10 16:00 UTC by Abse2001

2024-11-10 18:22 UTC, seveibar commented on lib/index.ts
> +export const pushbuttonProps = commonComponentProps.extend({})
```suggestion
export const pushButtonProps = commonComponentProps.extend({})
```

2024-11-10 18:23 UTC, seveibar requested changes
Create a separate file, there is a notice at the top of lib/index.ts

2024-11-10 18:24 UTC, Abse2001 commented
Will do

2024-11-11 16:56 UTC, seveibar requested changes

2024-11-11 16:56 UTC, seveibar commented on lib/components/pushbutton.ts
> +import { commonComponentProps } from "lib/common/layout"
filename should match casing `push-button.ts`

2024-11-11 17:03 UTC, seveibar approved these changes

2024-11-11 17:03 UTC, merged